In [15]:
import numpy as np
import operator
import pandas as pd # Для работы с данными
import scipy.stats # При работе со статистикой
import matplotlib.pyplot as plt  # Библиотека для визуализации результатов
%matplotlib inline
from sklearn.linear_model import LinearRegression # линейная регрессия
from sklearn.linear_model import LogisticRegression # логистическая регрессия

In [4]:
data = pd.read_csv('adult.csv', delimiter = ',')
data.head()

age         workclass  fnlwgt  education  education-num  \
0    2         State-gov   77516  Bachelors             13   
1    3  Self-emp-not-inc   83311  Bachelors             13   
2    2           Private  215646    HS-grad              9   
3    3           Private  234721       11th              7   
4    1           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capitalgain  capitalloss  hoursperweek native-country  class  
0            1            0             2  United-States  <=50K  
1            0            0             0  United-States  <=50K  
2            0            0             2  United-States  <=50K  
3            0            0             2  United-States  <=50K  
4            0            0             2           Cuba  <=50K

In [20]:
# попробуем выбрать какие-нибудь признаки, для начала
selectedColumns = data [['education','race']]

In [22]:
# столбец 'education','race' - категориальная переменная
# переведем ее в значения 0 и 1, добавив столбцы с соответствующими названиями
X = pd.get_dummies (selectedColumns, columns = ['education','race'])


In [23]:
# целевая переменная (столбец class) снова является категориальной 
# переведем значения столбца в числа, оставив один столбец

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [24]:
le.fit( data['class'])

LabelEncoder()

In [25]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [26]:
le.inverse_transform([1, 0, 1])

array(['>50K', '<=50K', '>50K'], dtype=object)

In [27]:
# записываем в таргетную переменную y преобразованный столбец class

y = pd.Series (data = le.transform(data['class']))
y.head()

0    0
1    0
2    0
3    0
4    0
dtype: int32

In [45]:
from sklearn.pipeline import make_pipeline # используем пайплайны для удобства
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split 

#model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))

In [46]:
model = LogisticRegression() # берем в качестве модели логистическую регресиию из scikit-learn

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [48]:
# обучаем на части датасета (train)

model.fit(X_train, y_train)
predictions = model.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [49]:
predictions[:100] # посмотрим как выглядят наши предсказание

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [33]:
model.predict(X_test) # получаем массив

array([0, 0, 0, ..., 0, 0, 0])

In [52]:
model.predict_proba(X_test)

array([[0.83026844, 0.16973156],
       [0.92358969, 0.07641031],
       [0.90942109, 0.09057891],
       ...,
       [0.90942109, 0.09057891],
       [0.83026844, 0.16973156],
       [0.92358969, 0.07641031]])

In [35]:
model.score(X_train, y_train) 

0.7818011641171136

In [36]:
model.score(X_test,y_test)

0.7770422439090972

In [39]:
from sklearn.svm import SVC
# используем пайплайны
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [40]:
clf.score(X_train, y_train) 

0.7818011641171136

In [41]:
clf.score(X_test, y_test)

0.7770422439090972

In [42]:
svc = SVC(gamma='auto')
svc.fit(X_train, y_train)

SVC(gamma='auto')

In [43]:
svc.score(X_train, y_train)

0.7813331773377402

In [44]:
svc.score(X_test, y_test)

0.7760185627516549